project_id = "onlasynzdryijgktfvvh"

[functions.generate-formula]
verify_jwt = true

[functions.lemonsqueezy-webhook]
verify_jwt = false

[functions.check-expired-plans]
verify_jwt = false

[functions.manage-api-key]
verify_jwt = true

[functions.sheets-addon-generate]
verify_jwt = false