// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onlasynzdryijgktfvvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ubGFzeW56ZHJ5aWpna3RmdnZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTM3NzMsImV4cCI6MjA3Mzc4OTc3M30.6smjzvHi-D95EKZscOLhAWfwMzrlkoF13DRdjxp46xo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});